#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_OrigCatalog_Nissan_Test
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OriginalCatalog")]
	public partial class NissanDbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertnissan_engine(nissan_engine instance);
    partial void Updatenissan_engine(nissan_engine instance);
    partial void Deletenissan_engine(nissan_engine instance);
    partial void Insertnissan_lvl1(nissan_lvl1 instance);
    partial void Updatenissan_lvl1(nissan_lvl1 instance);
    partial void Deletenissan_lvl1(nissan_lvl1 instance);
    partial void Insertnissan_lvl2(nissan_lvl2 instance);
    partial void Updatenissan_lvl2(nissan_lvl2 instance);
    partial void Deletenissan_lvl2(nissan_lvl2 instance);
    partial void Insertnissan_model(nissan_model instance);
    partial void Updatenissan_model(nissan_model instance);
    partial void Deletenissan_model(nissan_model instance);
    partial void InsertElcats_account(Elcats_account instance);
    partial void UpdateElcats_account(Elcats_account instance);
    partial void DeleteElcats_account(Elcats_account instance);
    partial void InsertProxy(Proxy instance);
    partial void UpdateProxy(Proxy instance);
    partial void DeleteProxy(Proxy instance);
    partial void Insertscheme(scheme instance);
    partial void Updatescheme(scheme instance);
    partial void Deletescheme(scheme instance);
    partial void InsertschemeImage(schemeImage instance);
    partial void UpdateschemeImage(schemeImage instance);
    partial void DeleteschemeImage(schemeImage instance);
    #endregion
		
		public NissanDbDataContext() : 
				base(global::EF_OrigCatalog_Nissan_Test.Properties.Settings.Default.OriginalCatalogConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public NissanDbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NissanDbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NissanDbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NissanDbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<nissan_engine> nissan_engines
		{
			get
			{
				return this.GetTable<nissan_engine>();
			}
		}
		
		public System.Data.Linq.Table<nissan_lvl1> nissan_lvl1s
		{
			get
			{
				return this.GetTable<nissan_lvl1>();
			}
		}
		
		public System.Data.Linq.Table<nissan_lvl2> nissan_lvl2s
		{
			get
			{
				return this.GetTable<nissan_lvl2>();
			}
		}
		
		public System.Data.Linq.Table<nissan_model> nissan_models
		{
			get
			{
				return this.GetTable<nissan_model>();
			}
		}
		
		public System.Data.Linq.Table<Elcats_account> Elcats_accounts
		{
			get
			{
				return this.GetTable<Elcats_account>();
			}
		}
		
		public System.Data.Linq.Table<Proxy> Proxies
		{
			get
			{
				return this.GetTable<Proxy>();
			}
		}
		
		public System.Data.Linq.Table<scheme> schemes
		{
			get
			{
				return this.GetTable<scheme>();
			}
		}
		
		public System.Data.Linq.Table<schemeImage> schemeImages
		{
			get
			{
				return this.GetTable<schemeImage>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nissan_engines")]
	public partial class nissan_engine : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _model_id;
		
		private string _body;
		
		private string _engine;
		
		private string _region;
		
		private string _complete_set;
		
		private string _transmission;
		
		private string _seats;
		
		private string _roof;
		
		private string _power;
		
		private string _wheels;
		
		private string _type;
		
		private string _frame;
		
		private string _speed;
		
		private string _bed_type;
		
		private string _capacity;
		
		private string _cab;
		
		private string _eng_spec;
		
		private string _equipment;
		
		private string _drive;
		
		private string _zone;
		
		private string _intake;
		
		private string _p_load;
		
		private string _passengr;
		
		private string _length;
		
		private string _duty;
		
		private string _year;
		
		private string _region_drive;
		
		private string _engine_power;
		
		private string _doors;
		
		private string _whl_area;
		
		private string _dest;
		
		private string _axis;
		
		private string _exhaust_control;
		
		private string _sus;
		
		private string _style;
		
		private string _fuel;
		
		private string _suspension;
		
		private string _battery;
		
		private string _trim_mtl;
		
		private string _series;
		
		private string _save_gas;
		
		private string _link;
		
		private int _Is_Done;
		
		private EntityRef<nissan_model> _nissan_model;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onmodel_idChanging(int value);
    partial void Onmodel_idChanged();
    partial void OnbodyChanging(string value);
    partial void OnbodyChanged();
    partial void OnengineChanging(string value);
    partial void OnengineChanged();
    partial void OnregionChanging(string value);
    partial void OnregionChanged();
    partial void Oncomplete_setChanging(string value);
    partial void Oncomplete_setChanged();
    partial void OntransmissionChanging(string value);
    partial void OntransmissionChanged();
    partial void OnseatsChanging(string value);
    partial void OnseatsChanged();
    partial void OnroofChanging(string value);
    partial void OnroofChanged();
    partial void OnpowerChanging(string value);
    partial void OnpowerChanged();
    partial void OnwheelsChanging(string value);
    partial void OnwheelsChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OnframeChanging(string value);
    partial void OnframeChanged();
    partial void OnspeedChanging(string value);
    partial void OnspeedChanged();
    partial void Onbed_typeChanging(string value);
    partial void Onbed_typeChanged();
    partial void OncapacityChanging(string value);
    partial void OncapacityChanged();
    partial void OncabChanging(string value);
    partial void OncabChanged();
    partial void Oneng_specChanging(string value);
    partial void Oneng_specChanged();
    partial void OnequipmentChanging(string value);
    partial void OnequipmentChanged();
    partial void OndriveChanging(string value);
    partial void OndriveChanged();
    partial void OnzoneChanging(string value);
    partial void OnzoneChanged();
    partial void OnintakeChanging(string value);
    partial void OnintakeChanged();
    partial void Onp_loadChanging(string value);
    partial void Onp_loadChanged();
    partial void OnpassengrChanging(string value);
    partial void OnpassengrChanged();
    partial void OnlengthChanging(string value);
    partial void OnlengthChanged();
    partial void OndutyChanging(string value);
    partial void OndutyChanged();
    partial void OnyearChanging(string value);
    partial void OnyearChanged();
    partial void Onregion_driveChanging(string value);
    partial void Onregion_driveChanged();
    partial void Onengine_powerChanging(string value);
    partial void Onengine_powerChanged();
    partial void OndoorsChanging(string value);
    partial void OndoorsChanged();
    partial void Onwhl_areaChanging(string value);
    partial void Onwhl_areaChanged();
    partial void OndestChanging(string value);
    partial void OndestChanged();
    partial void OnaxisChanging(string value);
    partial void OnaxisChanged();
    partial void Onexhaust_controlChanging(string value);
    partial void Onexhaust_controlChanged();
    partial void OnsusChanging(string value);
    partial void OnsusChanged();
    partial void OnstyleChanging(string value);
    partial void OnstyleChanged();
    partial void OnfuelChanging(string value);
    partial void OnfuelChanged();
    partial void OnsuspensionChanging(string value);
    partial void OnsuspensionChanged();
    partial void OnbatteryChanging(string value);
    partial void OnbatteryChanged();
    partial void Ontrim_mtlChanging(string value);
    partial void Ontrim_mtlChanged();
    partial void OnseriesChanging(string value);
    partial void OnseriesChanged();
    partial void Onsave_gasChanging(string value);
    partial void Onsave_gasChanged();
    partial void OnlinkChanging(string value);
    partial void OnlinkChanged();
    partial void OnIs_DoneChanging(int value);
    partial void OnIs_DoneChanged();
    #endregion
		
		public nissan_engine()
		{
			this._nissan_model = default(EntityRef<nissan_model>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_model_id", DbType="Int NOT NULL")]
		public int model_id
		{
			get
			{
				return this._model_id;
			}
			set
			{
				if ((this._model_id != value))
				{
					if (this._nissan_model.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onmodel_idChanging(value);
					this.SendPropertyChanging();
					this._model_id = value;
					this.SendPropertyChanged("model_id");
					this.Onmodel_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_body", DbType="NVarChar(255)")]
		public string body
		{
			get
			{
				return this._body;
			}
			set
			{
				if ((this._body != value))
				{
					this.OnbodyChanging(value);
					this.SendPropertyChanging();
					this._body = value;
					this.SendPropertyChanged("body");
					this.OnbodyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_engine", DbType="NVarChar(255)")]
		public string engine
		{
			get
			{
				return this._engine;
			}
			set
			{
				if ((this._engine != value))
				{
					this.OnengineChanging(value);
					this.SendPropertyChanging();
					this._engine = value;
					this.SendPropertyChanged("engine");
					this.OnengineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_region", DbType="NVarChar(255)")]
		public string region
		{
			get
			{
				return this._region;
			}
			set
			{
				if ((this._region != value))
				{
					this.OnregionChanging(value);
					this.SendPropertyChanging();
					this._region = value;
					this.SendPropertyChanged("region");
					this.OnregionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_complete_set", DbType="NVarChar(255)")]
		public string complete_set
		{
			get
			{
				return this._complete_set;
			}
			set
			{
				if ((this._complete_set != value))
				{
					this.Oncomplete_setChanging(value);
					this.SendPropertyChanging();
					this._complete_set = value;
					this.SendPropertyChanged("complete_set");
					this.Oncomplete_setChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transmission", DbType="NVarChar(255)")]
		public string transmission
		{
			get
			{
				return this._transmission;
			}
			set
			{
				if ((this._transmission != value))
				{
					this.OntransmissionChanging(value);
					this.SendPropertyChanging();
					this._transmission = value;
					this.SendPropertyChanged("transmission");
					this.OntransmissionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seats", DbType="NVarChar(255)")]
		public string seats
		{
			get
			{
				return this._seats;
			}
			set
			{
				if ((this._seats != value))
				{
					this.OnseatsChanging(value);
					this.SendPropertyChanging();
					this._seats = value;
					this.SendPropertyChanged("seats");
					this.OnseatsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roof", DbType="NVarChar(255)")]
		public string roof
		{
			get
			{
				return this._roof;
			}
			set
			{
				if ((this._roof != value))
				{
					this.OnroofChanging(value);
					this.SendPropertyChanging();
					this._roof = value;
					this.SendPropertyChanged("roof");
					this.OnroofChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_power", DbType="NVarChar(255)")]
		public string power
		{
			get
			{
				return this._power;
			}
			set
			{
				if ((this._power != value))
				{
					this.OnpowerChanging(value);
					this.SendPropertyChanging();
					this._power = value;
					this.SendPropertyChanged("power");
					this.OnpowerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wheels", DbType="NVarChar(255)")]
		public string wheels
		{
			get
			{
				return this._wheels;
			}
			set
			{
				if ((this._wheels != value))
				{
					this.OnwheelsChanging(value);
					this.SendPropertyChanging();
					this._wheels = value;
					this.SendPropertyChanged("wheels");
					this.OnwheelsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(255)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_frame", DbType="NVarChar(255)")]
		public string frame
		{
			get
			{
				return this._frame;
			}
			set
			{
				if ((this._frame != value))
				{
					this.OnframeChanging(value);
					this.SendPropertyChanging();
					this._frame = value;
					this.SendPropertyChanged("frame");
					this.OnframeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_speed", DbType="NVarChar(255)")]
		public string speed
		{
			get
			{
				return this._speed;
			}
			set
			{
				if ((this._speed != value))
				{
					this.OnspeedChanging(value);
					this.SendPropertyChanging();
					this._speed = value;
					this.SendPropertyChanged("speed");
					this.OnspeedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bed_type", DbType="NVarChar(255)")]
		public string bed_type
		{
			get
			{
				return this._bed_type;
			}
			set
			{
				if ((this._bed_type != value))
				{
					this.Onbed_typeChanging(value);
					this.SendPropertyChanging();
					this._bed_type = value;
					this.SendPropertyChanged("bed_type");
					this.Onbed_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_capacity", DbType="NVarChar(255)")]
		public string capacity
		{
			get
			{
				return this._capacity;
			}
			set
			{
				if ((this._capacity != value))
				{
					this.OncapacityChanging(value);
					this.SendPropertyChanging();
					this._capacity = value;
					this.SendPropertyChanged("capacity");
					this.OncapacityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cab", DbType="NVarChar(255)")]
		public string cab
		{
			get
			{
				return this._cab;
			}
			set
			{
				if ((this._cab != value))
				{
					this.OncabChanging(value);
					this.SendPropertyChanging();
					this._cab = value;
					this.SendPropertyChanged("cab");
					this.OncabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eng_spec", DbType="NVarChar(255)")]
		public string eng_spec
		{
			get
			{
				return this._eng_spec;
			}
			set
			{
				if ((this._eng_spec != value))
				{
					this.Oneng_specChanging(value);
					this.SendPropertyChanging();
					this._eng_spec = value;
					this.SendPropertyChanged("eng_spec");
					this.Oneng_specChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_equipment", DbType="NVarChar(255)")]
		public string equipment
		{
			get
			{
				return this._equipment;
			}
			set
			{
				if ((this._equipment != value))
				{
					this.OnequipmentChanging(value);
					this.SendPropertyChanging();
					this._equipment = value;
					this.SendPropertyChanged("equipment");
					this.OnequipmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_drive", DbType="NVarChar(255)")]
		public string drive
		{
			get
			{
				return this._drive;
			}
			set
			{
				if ((this._drive != value))
				{
					this.OndriveChanging(value);
					this.SendPropertyChanging();
					this._drive = value;
					this.SendPropertyChanged("drive");
					this.OndriveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zone", DbType="NVarChar(255)")]
		public string zone
		{
			get
			{
				return this._zone;
			}
			set
			{
				if ((this._zone != value))
				{
					this.OnzoneChanging(value);
					this.SendPropertyChanging();
					this._zone = value;
					this.SendPropertyChanged("zone");
					this.OnzoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intake", DbType="NVarChar(255)")]
		public string intake
		{
			get
			{
				return this._intake;
			}
			set
			{
				if ((this._intake != value))
				{
					this.OnintakeChanging(value);
					this.SendPropertyChanging();
					this._intake = value;
					this.SendPropertyChanged("intake");
					this.OnintakeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_load", DbType="NVarChar(255)")]
		public string p_load
		{
			get
			{
				return this._p_load;
			}
			set
			{
				if ((this._p_load != value))
				{
					this.Onp_loadChanging(value);
					this.SendPropertyChanging();
					this._p_load = value;
					this.SendPropertyChanged("p_load");
					this.Onp_loadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passengr", DbType="NVarChar(255)")]
		public string passengr
		{
			get
			{
				return this._passengr;
			}
			set
			{
				if ((this._passengr != value))
				{
					this.OnpassengrChanging(value);
					this.SendPropertyChanging();
					this._passengr = value;
					this.SendPropertyChanged("passengr");
					this.OnpassengrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_length", DbType="NVarChar(255)")]
		public string length
		{
			get
			{
				return this._length;
			}
			set
			{
				if ((this._length != value))
				{
					this.OnlengthChanging(value);
					this.SendPropertyChanging();
					this._length = value;
					this.SendPropertyChanged("length");
					this.OnlengthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duty", DbType="NVarChar(255)")]
		public string duty
		{
			get
			{
				return this._duty;
			}
			set
			{
				if ((this._duty != value))
				{
					this.OndutyChanging(value);
					this.SendPropertyChanging();
					this._duty = value;
					this.SendPropertyChanged("duty");
					this.OndutyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_year", DbType="NVarChar(255)")]
		public string year
		{
			get
			{
				return this._year;
			}
			set
			{
				if ((this._year != value))
				{
					this.OnyearChanging(value);
					this.SendPropertyChanging();
					this._year = value;
					this.SendPropertyChanged("year");
					this.OnyearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_region_drive", DbType="NVarChar(255)")]
		public string region_drive
		{
			get
			{
				return this._region_drive;
			}
			set
			{
				if ((this._region_drive != value))
				{
					this.Onregion_driveChanging(value);
					this.SendPropertyChanging();
					this._region_drive = value;
					this.SendPropertyChanged("region_drive");
					this.Onregion_driveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_engine_power", DbType="NVarChar(255)")]
		public string engine_power
		{
			get
			{
				return this._engine_power;
			}
			set
			{
				if ((this._engine_power != value))
				{
					this.Onengine_powerChanging(value);
					this.SendPropertyChanging();
					this._engine_power = value;
					this.SendPropertyChanged("engine_power");
					this.Onengine_powerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doors", DbType="NVarChar(255)")]
		public string doors
		{
			get
			{
				return this._doors;
			}
			set
			{
				if ((this._doors != value))
				{
					this.OndoorsChanging(value);
					this.SendPropertyChanging();
					this._doors = value;
					this.SendPropertyChanged("doors");
					this.OndoorsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_whl_area", DbType="NVarChar(255)")]
		public string whl_area
		{
			get
			{
				return this._whl_area;
			}
			set
			{
				if ((this._whl_area != value))
				{
					this.Onwhl_areaChanging(value);
					this.SendPropertyChanging();
					this._whl_area = value;
					this.SendPropertyChanged("whl_area");
					this.Onwhl_areaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dest", DbType="NVarChar(255)")]
		public string dest
		{
			get
			{
				return this._dest;
			}
			set
			{
				if ((this._dest != value))
				{
					this.OndestChanging(value);
					this.SendPropertyChanging();
					this._dest = value;
					this.SendPropertyChanged("dest");
					this.OndestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_axis", DbType="NVarChar(255)")]
		public string axis
		{
			get
			{
				return this._axis;
			}
			set
			{
				if ((this._axis != value))
				{
					this.OnaxisChanging(value);
					this.SendPropertyChanging();
					this._axis = value;
					this.SendPropertyChanged("axis");
					this.OnaxisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exhaust_control", DbType="NVarChar(255)")]
		public string exhaust_control
		{
			get
			{
				return this._exhaust_control;
			}
			set
			{
				if ((this._exhaust_control != value))
				{
					this.Onexhaust_controlChanging(value);
					this.SendPropertyChanging();
					this._exhaust_control = value;
					this.SendPropertyChanged("exhaust_control");
					this.Onexhaust_controlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sus", DbType="NVarChar(255)")]
		public string sus
		{
			get
			{
				return this._sus;
			}
			set
			{
				if ((this._sus != value))
				{
					this.OnsusChanging(value);
					this.SendPropertyChanging();
					this._sus = value;
					this.SendPropertyChanged("sus");
					this.OnsusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_style", DbType="NVarChar(255)")]
		public string style
		{
			get
			{
				return this._style;
			}
			set
			{
				if ((this._style != value))
				{
					this.OnstyleChanging(value);
					this.SendPropertyChanging();
					this._style = value;
					this.SendPropertyChanged("style");
					this.OnstyleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fuel", DbType="NVarChar(255)")]
		public string fuel
		{
			get
			{
				return this._fuel;
			}
			set
			{
				if ((this._fuel != value))
				{
					this.OnfuelChanging(value);
					this.SendPropertyChanging();
					this._fuel = value;
					this.SendPropertyChanged("fuel");
					this.OnfuelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_suspension", DbType="NVarChar(255)")]
		public string suspension
		{
			get
			{
				return this._suspension;
			}
			set
			{
				if ((this._suspension != value))
				{
					this.OnsuspensionChanging(value);
					this.SendPropertyChanging();
					this._suspension = value;
					this.SendPropertyChanged("suspension");
					this.OnsuspensionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_battery", DbType="NVarChar(255)")]
		public string battery
		{
			get
			{
				return this._battery;
			}
			set
			{
				if ((this._battery != value))
				{
					this.OnbatteryChanging(value);
					this.SendPropertyChanging();
					this._battery = value;
					this.SendPropertyChanged("battery");
					this.OnbatteryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trim_mtl", DbType="NVarChar(255)")]
		public string trim_mtl
		{
			get
			{
				return this._trim_mtl;
			}
			set
			{
				if ((this._trim_mtl != value))
				{
					this.Ontrim_mtlChanging(value);
					this.SendPropertyChanging();
					this._trim_mtl = value;
					this.SendPropertyChanged("trim_mtl");
					this.Ontrim_mtlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_series", DbType="NVarChar(255)")]
		public string series
		{
			get
			{
				return this._series;
			}
			set
			{
				if ((this._series != value))
				{
					this.OnseriesChanging(value);
					this.SendPropertyChanging();
					this._series = value;
					this.SendPropertyChanged("series");
					this.OnseriesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_save_gas", DbType="NVarChar(255)")]
		public string save_gas
		{
			get
			{
				return this._save_gas;
			}
			set
			{
				if ((this._save_gas != value))
				{
					this.Onsave_gasChanging(value);
					this.SendPropertyChanging();
					this._save_gas = value;
					this.SendPropertyChanged("save_gas");
					this.Onsave_gasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string link
		{
			get
			{
				return this._link;
			}
			set
			{
				if ((this._link != value))
				{
					this.OnlinkChanging(value);
					this.SendPropertyChanging();
					this._link = value;
					this.SendPropertyChanged("link");
					this.OnlinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Is_Done", DbType="Int NOT NULL")]
		public int Is_Done
		{
			get
			{
				return this._Is_Done;
			}
			set
			{
				if ((this._Is_Done != value))
				{
					this.OnIs_DoneChanging(value);
					this.SendPropertyChanging();
					this._Is_Done = value;
					this.SendPropertyChanged("Is_Done");
					this.OnIs_DoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nissan_model_nissan_engine", Storage="_nissan_model", ThisKey="model_id", OtherKey="id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public nissan_model nissan_model
		{
			get
			{
				return this._nissan_model.Entity;
			}
			set
			{
				nissan_model previousValue = this._nissan_model.Entity;
				if (((previousValue != value) 
							|| (this._nissan_model.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nissan_model.Entity = null;
						previousValue.nissan_engines.Remove(this);
					}
					this._nissan_model.Entity = value;
					if ((value != null))
					{
						value.nissan_engines.Add(this);
						this._model_id = value.id;
					}
					else
					{
						this._model_id = default(int);
					}
					this.SendPropertyChanged("nissan_model");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nissan_lvl1")]
	public partial class nissan_lvl1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private EntitySet<nissan_lvl2> _nissan_lvl2s;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public nissan_lvl1()
		{
			this._nissan_lvl2s = new EntitySet<nissan_lvl2>(new Action<nissan_lvl2>(this.attach_nissan_lvl2s), new Action<nissan_lvl2>(this.detach_nissan_lvl2s));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nissan_lvl1_nissan_lvl2", Storage="_nissan_lvl2s", ThisKey="id", OtherKey="lvl1_id")]
		public EntitySet<nissan_lvl2> nissan_lvl2s
		{
			get
			{
				return this._nissan_lvl2s;
			}
			set
			{
				this._nissan_lvl2s.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_nissan_lvl2s(nissan_lvl2 entity)
		{
			this.SendPropertyChanging();
			entity.nissan_lvl1 = this;
		}
		
		private void detach_nissan_lvl2s(nissan_lvl2 entity)
		{
			this.SendPropertyChanging();
			entity.nissan_lvl1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nissan_lvl2")]
	public partial class nissan_lvl2 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private int _lvl1_id;
		
		private EntityRef<nissan_lvl1> _nissan_lvl1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onlvl1_idChanging(int value);
    partial void Onlvl1_idChanged();
    #endregion
		
		public nissan_lvl2()
		{
			this._nissan_lvl1 = default(EntityRef<nissan_lvl1>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lvl1_id", DbType="Int NOT NULL")]
		public int lvl1_id
		{
			get
			{
				return this._lvl1_id;
			}
			set
			{
				if ((this._lvl1_id != value))
				{
					if (this._nissan_lvl1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onlvl1_idChanging(value);
					this.SendPropertyChanging();
					this._lvl1_id = value;
					this.SendPropertyChanged("lvl1_id");
					this.Onlvl1_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nissan_lvl1_nissan_lvl2", Storage="_nissan_lvl1", ThisKey="lvl1_id", OtherKey="id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public nissan_lvl1 nissan_lvl1
		{
			get
			{
				return this._nissan_lvl1.Entity;
			}
			set
			{
				nissan_lvl1 previousValue = this._nissan_lvl1.Entity;
				if (((previousValue != value) 
							|| (this._nissan_lvl1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nissan_lvl1.Entity = null;
						previousValue.nissan_lvl2s.Remove(this);
					}
					this._nissan_lvl1.Entity = value;
					if ((value != null))
					{
						value.nissan_lvl2s.Add(this);
						this._lvl1_id = value.id;
					}
					else
					{
						this._lvl1_id = default(int);
					}
					this.SendPropertyChanged("nissan_lvl1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nissan_models")]
	public partial class nissan_model : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _brand_id;
		
		private string _name;
		
		private string _date_start;
		
		private string _date_end;
		
		private string _region;
		
		private string _short_name;
		
		private string _modification;
		
		private string _link;
		
		private int _Is_Done;
		
		private EntitySet<nissan_engine> _nissan_engines;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onbrand_idChanging(int value);
    partial void Onbrand_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Ondate_startChanging(string value);
    partial void Ondate_startChanged();
    partial void Ondate_endChanging(string value);
    partial void Ondate_endChanged();
    partial void OnregionChanging(string value);
    partial void OnregionChanged();
    partial void Onshort_nameChanging(string value);
    partial void Onshort_nameChanged();
    partial void OnmodificationChanging(string value);
    partial void OnmodificationChanged();
    partial void OnlinkChanging(string value);
    partial void OnlinkChanged();
    partial void OnIs_DoneChanging(int value);
    partial void OnIs_DoneChanged();
    #endregion
		
		public nissan_model()
		{
			this._nissan_engines = new EntitySet<nissan_engine>(new Action<nissan_engine>(this.attach_nissan_engines), new Action<nissan_engine>(this.detach_nissan_engines));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brand_id", DbType="Int NOT NULL")]
		public int brand_id
		{
			get
			{
				return this._brand_id;
			}
			set
			{
				if ((this._brand_id != value))
				{
					this.Onbrand_idChanging(value);
					this.SendPropertyChanging();
					this._brand_id = value;
					this.SendPropertyChanged("brand_id");
					this.Onbrand_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_start", DbType="NVarChar(50)")]
		public string date_start
		{
			get
			{
				return this._date_start;
			}
			set
			{
				if ((this._date_start != value))
				{
					this.Ondate_startChanging(value);
					this.SendPropertyChanging();
					this._date_start = value;
					this.SendPropertyChanged("date_start");
					this.Ondate_startChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_end", DbType="NVarChar(50)")]
		public string date_end
		{
			get
			{
				return this._date_end;
			}
			set
			{
				if ((this._date_end != value))
				{
					this.Ondate_endChanging(value);
					this.SendPropertyChanging();
					this._date_end = value;
					this.SendPropertyChanged("date_end");
					this.Ondate_endChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_region", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string region
		{
			get
			{
				return this._region;
			}
			set
			{
				if ((this._region != value))
				{
					this.OnregionChanging(value);
					this.SendPropertyChanging();
					this._region = value;
					this.SendPropertyChanged("region");
					this.OnregionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_short_name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string short_name
		{
			get
			{
				return this._short_name;
			}
			set
			{
				if ((this._short_name != value))
				{
					this.Onshort_nameChanging(value);
					this.SendPropertyChanging();
					this._short_name = value;
					this.SendPropertyChanged("short_name");
					this.Onshort_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modification", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string modification
		{
			get
			{
				return this._modification;
			}
			set
			{
				if ((this._modification != value))
				{
					this.OnmodificationChanging(value);
					this.SendPropertyChanging();
					this._modification = value;
					this.SendPropertyChanged("modification");
					this.OnmodificationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string link
		{
			get
			{
				return this._link;
			}
			set
			{
				if ((this._link != value))
				{
					this.OnlinkChanging(value);
					this.SendPropertyChanging();
					this._link = value;
					this.SendPropertyChanged("link");
					this.OnlinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Is_Done", DbType="Int NOT NULL")]
		public int Is_Done
		{
			get
			{
				return this._Is_Done;
			}
			set
			{
				if ((this._Is_Done != value))
				{
					this.OnIs_DoneChanging(value);
					this.SendPropertyChanging();
					this._Is_Done = value;
					this.SendPropertyChanged("Is_Done");
					this.OnIs_DoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nissan_model_nissan_engine", Storage="_nissan_engines", ThisKey="id", OtherKey="model_id")]
		public EntitySet<nissan_engine> nissan_engines
		{
			get
			{
				return this._nissan_engines;
			}
			set
			{
				this._nissan_engines.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_nissan_engines(nissan_engine entity)
		{
			this.SendPropertyChanging();
			entity.nissan_model = this;
		}
		
		private void detach_nissan_engines(nissan_engine entity)
		{
			this.SendPropertyChanging();
			entity.nissan_model = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Elcats_account")]
	public partial class Elcats_account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _login;
		
		private string _password;
		
		private string _cookie;
		
		private int _isBanned;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnloginChanging(string value);
    partial void OnloginChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OncookieChanging(string value);
    partial void OncookieChanged();
    partial void OnisBannedChanging(int value);
    partial void OnisBannedChanged();
    #endregion
		
		public Elcats_account()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string login
		{
			get
			{
				return this._login;
			}
			set
			{
				if ((this._login != value))
				{
					this.OnloginChanging(value);
					this.SendPropertyChanging();
					this._login = value;
					this.SendPropertyChanged("login");
					this.OnloginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cookie", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string cookie
		{
			get
			{
				return this._cookie;
			}
			set
			{
				if ((this._cookie != value))
				{
					this.OncookieChanging(value);
					this.SendPropertyChanging();
					this._cookie = value;
					this.SendPropertyChanged("cookie");
					this.OncookieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isBanned", DbType="Int NOT NULL")]
		public int isBanned
		{
			get
			{
				return this._isBanned;
			}
			set
			{
				if ((this._isBanned != value))
				{
					this.OnisBannedChanging(value);
					this.SendPropertyChanging();
					this._isBanned = value;
					this.SendPropertyChanged("isBanned");
					this.OnisBannedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Proxy")]
	public partial class Proxy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _host;
		
		private string _port;
		
		private string _username;
		
		private string _password;
		
		private int _isWork;
		
		private int _isBanned;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnhostChanging(string value);
    partial void OnhostChanged();
    partial void OnportChanging(string value);
    partial void OnportChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnisWorkChanging(int value);
    partial void OnisWorkChanged();
    partial void OnisBannedChanging(int value);
    partial void OnisBannedChanged();
    #endregion
		
		public Proxy()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_host", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string host
		{
			get
			{
				return this._host;
			}
			set
			{
				if ((this._host != value))
				{
					this.OnhostChanging(value);
					this.SendPropertyChanging();
					this._host = value;
					this.SendPropertyChanged("host");
					this.OnhostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_port", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string port
		{
			get
			{
				return this._port;
			}
			set
			{
				if ((this._port != value))
				{
					this.OnportChanging(value);
					this.SendPropertyChanging();
					this._port = value;
					this.SendPropertyChanged("port");
					this.OnportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(255)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(255)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isWork", DbType="Int NOT NULL")]
		public int isWork
		{
			get
			{
				return this._isWork;
			}
			set
			{
				if ((this._isWork != value))
				{
					this.OnisWorkChanging(value);
					this.SendPropertyChanging();
					this._isWork = value;
					this.SendPropertyChanged("isWork");
					this.OnisWorkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isBanned", DbType="Int NOT NULL")]
		public int isBanned
		{
			get
			{
				return this._isBanned;
			}
			set
			{
				if ((this._isBanned != value))
				{
					this.OnisBannedChanging(value);
					this.SendPropertyChanging();
					this._isBanned = value;
					this.SendPropertyChanged("isBanned");
					this.OnisBannedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.scheme")]
	public partial class scheme : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _path;
		
		private System.Nullable<int> _schemeImage_id;
		
		private EntityRef<schemeImage> _schemeImage;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnpathChanging(string value);
    partial void OnpathChanged();
    partial void OnschemeImage_idChanging(System.Nullable<int> value);
    partial void OnschemeImage_idChanged();
    #endregion
		
		public scheme()
		{
			this._schemeImage = default(EntityRef<schemeImage>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(255)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_path", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string path
		{
			get
			{
				return this._path;
			}
			set
			{
				if ((this._path != value))
				{
					this.OnpathChanging(value);
					this.SendPropertyChanging();
					this._path = value;
					this.SendPropertyChanged("path");
					this.OnpathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schemeImage_id", DbType="Int")]
		public System.Nullable<int> schemeImage_id
		{
			get
			{
				return this._schemeImage_id;
			}
			set
			{
				if ((this._schemeImage_id != value))
				{
					if (this._schemeImage.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnschemeImage_idChanging(value);
					this.SendPropertyChanging();
					this._schemeImage_id = value;
					this.SendPropertyChanged("schemeImage_id");
					this.OnschemeImage_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="schemeImage_scheme", Storage="_schemeImage", ThisKey="schemeImage_id", OtherKey="id", IsForeignKey=true, DeleteRule="SET NULL")]
		public schemeImage schemeImage
		{
			get
			{
				return this._schemeImage.Entity;
			}
			set
			{
				schemeImage previousValue = this._schemeImage.Entity;
				if (((previousValue != value) 
							|| (this._schemeImage.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._schemeImage.Entity = null;
						previousValue.schemes.Remove(this);
					}
					this._schemeImage.Entity = value;
					if ((value != null))
					{
						value.schemes.Add(this);
						this._schemeImage_id = value.id;
					}
					else
					{
						this._schemeImage_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("schemeImage");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.schemeImage")]
	public partial class schemeImage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _MD5;
		
		private int _isOnAzure;
		
		private EntitySet<scheme> _schemes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnMD5Changing(string value);
    partial void OnMD5Changed();
    partial void OnisOnAzureChanging(int value);
    partial void OnisOnAzureChanged();
    #endregion
		
		public schemeImage()
		{
			this._schemes = new EntitySet<scheme>(new Action<scheme>(this.attach_schemes), new Action<scheme>(this.detach_schemes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MD5", DbType="NVarChar(255)")]
		public string MD5
		{
			get
			{
				return this._MD5;
			}
			set
			{
				if ((this._MD5 != value))
				{
					this.OnMD5Changing(value);
					this.SendPropertyChanging();
					this._MD5 = value;
					this.SendPropertyChanged("MD5");
					this.OnMD5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isOnAzure", DbType="Int NOT NULL")]
		public int isOnAzure
		{
			get
			{
				return this._isOnAzure;
			}
			set
			{
				if ((this._isOnAzure != value))
				{
					this.OnisOnAzureChanging(value);
					this.SendPropertyChanging();
					this._isOnAzure = value;
					this.SendPropertyChanged("isOnAzure");
					this.OnisOnAzureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="schemeImage_scheme", Storage="_schemes", ThisKey="id", OtherKey="schemeImage_id")]
		public EntitySet<scheme> schemes
		{
			get
			{
				return this._schemes;
			}
			set
			{
				this._schemes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_schemes(scheme entity)
		{
			this.SendPropertyChanging();
			entity.schemeImage = this;
		}
		
		private void detach_schemes(scheme entity)
		{
			this.SendPropertyChanging();
			entity.schemeImage = null;
		}
	}
}
#pragma warning restore 1591
